# Generated by Django 4.2.7 on 2023-12-01 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import galtech.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/avatar.png', null=True, upload_to=galtech.models.unique_name)),
                ('create_at', models.DateField(auto_now=True, null=True)),
                ('update_at', models.DateField(auto_now=True, null=True)),
                ('delete_at', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
