# Generated by Django 4.2.7 on 2023-12-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galtech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_fee', models.CharField(max_length=255)),
                ('course_description', models.TextField()),
                ('course_type', models.BooleanField()),
                ('course_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
