# Generated by Django 4.2.7 on 2023-12-13 05:08

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galtech', '0008_video_delete_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=models.CharField(max_length=250), editable=False, populate_from='course_name', unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
