# Generated by Django 4.2.7 on 2023-12-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galtech', '0010_alter_courses_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='slug',
        ),
    ]
